version: 2
jobs:
  build:
    docker:
      #- image: circleci/php:7.1.5-browsers
      #- image: circleci/php:5.6.30-apache-browsers
      - image: circleci/php:7.1-cli

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run: php artisan key:generate

      - run: php artisan config:clear

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: vendor/bin/phpunit
